### ISSUE TITLE
regarding two sequentially placed convolutional layers

### ISSUE THREAD

**Issue by surfreta** [imlab-uiip/keras-segnet#3]
Hi, with respect to this segnet model, we can see that in each building block of encoder part, there are always two convolutional layers following each other before a maxpooling layer. For instance,

```
Convolution2D(64, kernel, kernel, border_mode='same', input_shape=(1, img_h, img_w)),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(64, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    MaxPooling2D(),

```

I am not very clear about the real logic of having two convolutional layers following each other. Why not just having a combined convolutional layer. What's the strength of having this kind of design shown in Segnet architecture.

**Comment by gakarak** [comment]
Hi, @surfreta 
Please see Section 2.3 ("Discussion", first paragraph) of the article:
[Very Deep Convolutional Networks for Large-Scale Image Recognition](https://arxiv.org/abs/1409.1556)
This is a basic article in Deep Learning (from [**Visual Geometry Group Team**](http://www.robots.ox.ac.uk/~vgg/)).
