### ISSUE TITLE
IOError: Unable to open file (File signature not found)

### ISSUE THREAD

**Issue by y22ma** [imlab-uiip/keras-segnet#5]
Got the following error when I run the following command: `python SegNet.py `
```
Using Theano backend.
Using gpu device 0: GeForce GTX 1070 (CNMeM is disabled, cuDNN 5105)
/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)
Compiled: OK
Traceback (most recent call last):
  File "SegNet.py", line 118, in <module>
    autoencoder.load_weights('model_5l_weight_ep50.hdf5')
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2695, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2577)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/_objects.c:2536)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/build/h5py-nQFNYZ/h5py-2.6.0/h5py/h5f.c:1811)
IOError: Unable to open file (File signature not found)
```

**Comment by ghost** [comment]
Have you ever examined the size of your .hdf5 file? It should be something like 110+MB. If you download the whole ZIP package directly, the hdf5 file in it is only a few bytes and you need to download it separately.

**Comment by eclique** [comment]
Hi, @y22ma. I have updated the weight file, try loading it now.
However this is only an example and you would still need to train network for your tasks, so this weight file is not really important.

**Comment by Feifannaner** [comment]
thank you  @ghost

**Comment by bzamecnik** [comment]
In my case the problem was that weights were in git-lfs which was not activated. Thus there was only a small file like the following instead of the original file:

```
version https://git-lfs.github.com/spec/v1
oid sha256:48b9b0db5bc1a08e01447acbb7c559ed155a0283e0d80d2964acf16e41cd76ec
size 3510652
```

**Comment by hmshan** [comment]
In my case, the problem was that I did not close the file after writing variables.

**Comment by nasir3843** [comment]
@bzamecnik . Yes u r right. Could you please guide me how i can download the weights file in its full shape. I have cloned the repository as well as downloaded it by clicking download button. Still downloaded weights file are shown in bytes while its original size is 236 MB. I am testing this code 

https://github.com/experiencor/keras-yolo3

and file thatIi want to download is   keras-yolo3/zoo/kangaroo.h5

**Comment by bzamecnik** [comment]
Maybe let's try something like:
```
git lfs install
git lfs fetch
git lfs pull
```

**Comment by nasir3843** [comment]
Thanks alote for the help and sorry for my late response. 

I got this message in terminal after typing 'git lfs install'. 

(py35) im@nasir:~/object_detection/yolov3_R3/zoo$ git lfs install
git: 'lfs' is not a git command. See 'git --help'.

Did you mean this?
	log

**Comment by reynierhdez** [comment]
Hi!

`git lfs fetch` returns the following error:

fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/imlab-uiip/keras-segnet.git/info/lfs'
