### ISSUE TITLE
Generating error when converting script to python 3

### ISSUE THREAD

**Issue by ishiry** [imlab-uiip/keras-segnet#7]
I am trying to run this in windows python 3 with tensor`flow backend(somehow my theano backend fail to utilize gpu). i converted print syntax in the ipython notebook and tried to run the script, it went well, but when i reached to "Loading and compiling model built with 'build_model.py'", received the following error. 
May I know what needs to be changed, based on this error. Also, what would be your suggestion if I would like to run the ipython using tensorflow backend with python 3

![error](https://cloud.githubusercontent.com/assets/13779813/24326263/aa9f9072-11e5-11e7-8ad4-535295fd8804.JPG)

`thank you in advance for looking into this issue.

**Comment by eclique** [comment]
This implementation works only with theano. To adapt it for tensorflow you would need to adjust operations with image shapes according to tensorflow dim_ordering.
